baseURL = 'https://tbd.tbd/'
languageCode = 'en-us'
title = 'My website'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A grounds for thoughts"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'GM'
homeIntroContent = """
@ryanology045
"""

# Collection to display on home
homeCollectionTitle = 'Writings'
homeCollection = 'writings'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
# [[params.social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/user/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

# [[params.social]]
# name = "github"
# url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writings"
url = "/writings"

[[params.menu]]
name = "quickthoughts"
url = "/quickthoughts"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
